--계정생성
CREATE USER c##member IDENTIFIED BY member1234
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##member;
GRANT CREATE VIEW, CREATE SYNONYM TO c##member;
GRANT UNLIMITED TABLESPACE TO c##spring;
--락 풀기
ALTER USER c##member ACCOUNT UNLOCK;